"""Generate and write suggested technique mappings for all discovered heuristics."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from project_paths import ProjectPaths

from .mapping_loader import load_curated_mappings
from .suggestion_scorer import ScoredSuggestion, score_suggestions

if TYPE_CHECKING:
    from knowledge.store import TechniqueStore

_log = logging.getLogger(__name__)
_DEFAULT_PATHS = ProjectPaths.default()

_DEFAULT_OUTPUT = _DEFAULT_PATHS.data_dir / "mapping_suggestions.toml"


def generate_mapping_suggestions(
    store: TechniqueStore,
    *,
    threshold: float = 0.40,
    top_k: int = 10,
    output_path: Path | None = None,
) -> dict[str, int]:
    """Score all heuristics and write mapping_suggestions.toml.

    Parameters
    ----------
    store:
        An open TechniqueStore with embeddings already computed.
    threshold:
        Minimum composite score to include a suggestion.
    top_k:
        Maximum suggestions per heuristic.
    output_path:
        Where to write the TOML. Defaults to ``data/threat_intel/mapping_suggestions.toml``.

    Returns
    -------
    dict mapping rule_id → count of accepted suggestions.  Also includes a
    ``"_total"`` key with the grand total.
    """
    from knowledge.embedder import SentenceTransformerEmbedder
    from knowledge.index import TechniqueIndex
    from knowledge.vector_index import VectorIndex

    from .heuristics import discovered_heuristics

    output_path = output_path or _DEFAULT_OUTPUT

    embedder = SentenceTransformerEmbedder()
    vec_idx = VectorIndex(store, embedder.model_name)

    if not vec_idx.is_populated:
        _log.warning("No embeddings in store — skipping suggestion generation.")
        return {"_total": 0}

    tech_idx = TechniqueIndex(store)
    heuristics = discovered_heuristics()

    all_suggestions: list[tuple[str, ScoredSuggestion]] = []
    counts: dict[str, int] = {}

    for h in heuristics:
        curated = load_curated_mappings(h.rule_id, index=tech_idx)
        query_text = f"{h.name}. {h.description}"

        suggestions = score_suggestions(
            rule_id=h.rule_id,
            heuristic_text=query_text,
            embedder=embedder,
            vector_index=vec_idx,
            technique_index=tech_idx,
            curated_mappings=curated,
            target_frameworks=h.frameworks,
            top_k=top_k,
        )
        accepted = [s for s in suggestions if s.composite_score >= threshold]
        counts[h.rule_id] = len(accepted)
        for s in accepted:
            all_suggestions.append((h.rule_id, s))

    counts["_total"] = sum(v for k, v in counts.items() if k != "_total")

    _write_suggestions_toml(all_suggestions, output_path, threshold=threshold, top_k=top_k)
    _log.info(
        "Wrote %d suggestions for %d heuristics to %s",
        counts["_total"],
        len(heuristics),
        output_path,
    )
    return counts


def _write_suggestions_toml(
    suggestions: list[tuple[str, ScoredSuggestion]],
    path: Path,
    *,
    threshold: float,
    top_k: int,
) -> None:
    """Serialize suggestions as a mapping_suggestions.toml file."""
    now = datetime.now(UTC).isoformat()
    lines: list[str] = [
        "# Auto-generated by: threatforge sync --map-heuristics",
        f"# Generated: {now}",
        f"# Threshold: {threshold} | Top-k: {top_k}",
        "",
    ]

    for rule_id, s in suggestions:
        lines.append("[[mappings]]")
        lines.append(f'rule_id = "{rule_id}"')
        lines.append(f'technique_id = "{s.technique_id}"')
        lines.append(f'framework = "{s.framework}"')
        lines.append(f'tactic = "{s.tactic}"')
        lines.append(f'rationale = "{s.explanation}"')
        lines.append(f'mapping_type = "suggested"')
        lines.append(f"composite_score = {s.composite_score:.4f}")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
