"""Generate and write suggested technique mappings for all discovered heuristics."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from project_paths import ProjectPaths
from toml_utils import toml_scalar, toml_string

from .mapping_loader import load_curated_mappings
from .graphrag_scorer import GraphRAGSuggestion

if TYPE_CHECKING:
    from knowledge.store import TechniqueStore

_log = logging.getLogger(__name__)
_DEFAULT_PATHS = ProjectPaths.default()

_DEFAULT_OUTPUT = _DEFAULT_PATHS.data_dir / "mapping_suggestions.toml"


def generate_mapping_suggestions(
    store: TechniqueStore,
    *,
    threshold: float = 0.40,
    top_k: int = 10,
    output_path: Path | None = None,
) -> dict[str, int]:
    """Score all heuristics and write mapping_suggestions.toml.

    Parameters
    ----------
    store:
        An open TechniqueStore with embeddings already computed.
    threshold:
        Minimum composite score to include a suggestion.
    top_k:
        Maximum suggestions per heuristic.
    output_path:
        Where to write the TOML. Defaults to ``data/threat_intel/mapping_suggestions.toml``.

    Returns
    -------
    dict mapping rule_id → count of accepted suggestions.  Also includes a
    ``"_total"`` key with the grand total.
    """
    from graph.neo4j_client import Neo4jClient, Neo4jConfig
    from knowledge.embedder import SentenceTransformerEmbedder
    from knowledge.index import TechniqueIndex

    from .heuristics import discovered_heuristics
    from .mapping_engine import graphrag_score_suggestions

    output_path = output_path or _DEFAULT_OUTPUT

    embedder = SentenceTransformerEmbedder()
    tech_idx = TechniqueIndex(store)
    heuristics = discovered_heuristics()
    config = Neo4jConfig.from_env()
    client = Neo4jClient(config)
    client.verify_connectivity()

    try:
        all_suggestions: list[tuple[str, GraphRAGSuggestion]] = []
        counts: dict[str, int] = {}

        for h in heuristics:
            curated = load_curated_mappings(h.rule_id, index=tech_idx)
            query_text = f"{h.name}. {h.description}"
            accepted = graphrag_score_suggestions(
                rule_id=h.rule_id,
                heuristic_text=query_text,
                neo4j_client=client,
                embedder=embedder,
                curated_mappings=curated,
                target_frameworks=h.frameworks,
                top_k=top_k,
                threshold=threshold,
            )
            counts[h.rule_id] = len(accepted)
            for s in accepted:
                all_suggestions.append((h.rule_id, s))

        counts["_total"] = sum(v for k, v in counts.items() if k != "_total")

        _write_suggestions_toml(all_suggestions, output_path, threshold=threshold, top_k=top_k)
        _log.info(
            "Wrote %d suggestions for %d heuristics to %s",
            counts["_total"],
            len(heuristics),
            output_path,
        )
        return counts
    finally:
        if client is not None:
            client.close()


def _write_suggestions_toml(
    suggestions: list[tuple[str, GraphRAGSuggestion]],
    path: Path,
    *,
    threshold: float,
    top_k: int,
) -> None:
    """Serialize suggestions as a mapping_suggestions.toml file."""
    now = datetime.now(UTC).isoformat()
    lines: list[str] = [
        "# Auto-generated by: threatforge sync --map-heuristics",
        f"# Generated: {now}",
        f"# Threshold: {threshold} | Top-k: {top_k}",
        "",
    ]

    for rule_id, s in suggestions:
        lines.append("[[mappings]]")
        lines.append(f"rule_id = {toml_string(rule_id)}")
        lines.append(f"technique_id = {toml_string(s.technique_id)}")
        lines.append(f"framework = {toml_string(s.framework)}")
        lines.append(f"tactic = {toml_string(s.tactic)}")
        lines.append(f"rationale = {toml_string(s.explanation)}")
        lines.append(f'mapping_type = "suggested"')
        lines.append(f"composite_score = {toml_scalar(round(s.composite_score, 4))}")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
